apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-gateway-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
      - name: cloud-gateway-app
        image: gabriellfe/cloudservice:IMAGE_URL
        imagePullPolicy: Always
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            path: /livenessProbe
            port: 9090
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            path: /livenessProbe
            port: 9090
        ports:
        - containerPort: 9090
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: config-cm
                key: config_url
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-cm
                key: hostname
---

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: cloud-gateway-app
  ports:
  - port: 80
    targetPort: 9090

