apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service-app
        image: gabriellfe/orderservice:IMAGE_URL
        imagePullPolicy: Always
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            path: /livenessProbe
            port: 80
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            path: /livenessProbe
            port: 80
        ports:
        - containerPort: 8082
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-cm
              key: config_url
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: hostname
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address
---

apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8082
