apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: payment-service-app
    spec:
      containers:
      - name: payment-service-app
        image: gabriellfe/paymentservice:IMAGE_URL
        imagePullPolicy: Always
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            path: /livenessProbe
            port: 8081
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            path: /livenessProbe
            port: 8081
        ports:
        - containerPort: 8081
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-cm
              key: config_url
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: hostname
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address

---

apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service-app
  ports:
  - port: 80
    targetPort: 8081
