server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
      import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    gateway:
      routes:
        - id : ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
#         ROTAS COGNITO       
        - id : PAYMENT-SERVICE-COGNITO
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/cognito/payment/**
          filters:
            - CognitoFilter
            - StripPrefix=1            
        - id : PRODUCT-SERVICE-COGNITO
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/cognito/product/**
          filters:
            - CognitoFilter
            - StripPrefix=1   
        - id : ORDER-SERVICE-COGNITO
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/cognito/order/**
          filters:
            - CognitoFilter
            - StripPrefix=1
#okta:
#  oauth2:
#    issuer: https://dev-56986490.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oadpahd6mHnrmpgw5d7
#    client-secret: eI2THAvlUfCzwaezyagi2HUOQ1H7KccHgUTfLjF6NHuMrfZmHdyowcP4rmqF_SDq
#    scopes: openid, email, profile, offline_access
#    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eureka:8761/eureka}