server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/usuariodb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: cloud-gateway
  config:
      import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    gateway:
      routes:
      #         Estados   
        - id : AUTH-SERVICE-ESTADOS
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/estados
          filters:
            - BypassFilter
#         Bypass   
        - id : AUTH-SERVICE-COGNITO
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/user/login
          filters:
            - BypassFilter
        - id : CLIENT-SERVICE
          uri: lb://CLIENT-MANAGEMENT-SERVICE
          predicates:
            - Path=/client/**
          filters:
            - TokenFilter
        - id : ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - TokenFilter
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - TokenFilter
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - TokenFilter
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
          #         Bypass   
        - id : AUTH-SERVICE-TOKEN
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - TokenFilter
#         ROTAS COGNITO       
        - id : PAYMENT-SERVICE-COGNITO
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/cognito/payment/**
          filters:
            - CognitoFilter
            - StripPrefix=1            
        - id : PRODUCT-SERVICE-COGNITO
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/cognito/product/**
          filters:
            - CognitoFilter
            - StripPrefix=1   
        - id : ORDER-SERVICE-COGNITO
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/cognito/order/**
          filters:
            - CognitoFilter
            - StripPrefix=1
#okta:
#  oauth2:
#    issuer: https://dev-56986490.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oadpahd6mHnrmpgw5d7
#    client-secret: eI2THAvlUfCzwaezyagi2HUOQ1H7KccHgUTfLjF6NHuMrfZmHdyowcP4rmqF_SDq
#    scopes: openid, email, profile, offline_access
#    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eureka:8761/eureka}