server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/usuariodb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: cloud-gateway
  config:
      import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    gateway:
      routes:
#         Auth   
        - id : AUTH-SERVICE-PERFIL
          uri: http://auth-service-svc
          predicates:
            - Path=/user/perfil
          filters:
            - TokenFilter
#         Auth   
        - id : AUTH-SERVICE-REFRESH
          uri: http://auth-service-svc
          predicates:
            - Path=/user/refresh
          filters:
            - TokenFilter
#         Bypass   
        - id : AUTH-SERVICE-BYPASS
          uri: http://auth-service-svc
          predicates:
            - Path=/user/**
          filters:
            - BypassFilter
        - id : ORDER-SERVICE
          uri: http://order-service-svc
          predicates:
            - Path=/order/**
          filters:
            - TokenFilter
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
        - id: PAYMENT-SERVICE
          uri: http://payment-service-svc
          predicates:
            - Path=/payment/**
          filters:
            - TokenFilter
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
        - id: PRODUCT-SERVICE
          uri: http://product-service-svc
          predicates:
            - Path=/product/**
          filters:
            - TokenFilter
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
#         ROTAS COGNITO       
        - id : PAYMENT-SERVICE-COGNITO
          uri: http://payment-service-svc
          predicates:
            - Path=/cognito/payment/**
          filters:
            - CognitoFilter
            - StripPrefix=1            
        - id : PRODUCT-SERVICE-COGNITO
          uri: http://product-service-svc
          predicates:
            - Path=/cognito/product/**
          filters:
            - CognitoFilter
            - StripPrefix=1   
        - id : ORDER-SERVICE-COGNITO
          uri: http://order-service-svc
          predicates:
            - Path=/cognito/order/**
          filters:
            - CognitoFilter
            - StripPrefix=1
#okta:
#  oauth2:
#    issuer: https://dev-56986490.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oadpahd6mHnrmpgw5d7
#    client-secret: eI2THAvlUfCzwaezyagi2HUOQ1H7KccHgUTfLjF6NHuMrfZmHdyowcP4rmqF_SDq
#    scopes: openid, email, profile, offline_access
#    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eureka:8761/eureka}