server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: order-service
  config:
      import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

#  oauth2:
#    issuer: https://dev-56986490.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oadpahd6mHnrmpgw5d7
#    client-secret: eI2THAvlUfCzwaezyagi2HUOQ1H7KccHgUTfLjF6NHuMrfZmHdyowcP4rmqF_SDq
#    scopes: openid, email, profile, offline_access
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}